### ISSUE TITLE
Bugs in savenpy function in preprocess.py

### ISSUE THREAD

**Issue by MrPrajwalB** [hust-linyi/A-Two-Stage-Convolutional-Neural-Network-for-Pulmonary-Embolism-Detection-From-CTPA-Images#1]
The variables dilatedMask, bone_thresh and pad_value are used before declaration. Please fix the code from lines 127-130 in preprocess.py

**Comment by hust-linyi** [comment]
> The variables dilatedMask, bone_thresh and pad_value are used before declaration. Please fix the code from lines 127-130 in preprocess.py

@MrPrajwalB
I have commented out the code cause I did not use it. You can set bone_thresh and pad_value according to your own data (e.g. 300 and 170 on our data). Thanks!
